module.exports = {

	TransactionStatus: {
		SUCCESS: 'SUCCESS',
		FAILURE: 'FAILURE'
	},
	Procedure: {
		GET_ALL_BOOKING_DETAILS: 'GET_ALL_BOOKING_DETAILS',
		CREATE_BOOKING: 'CREATE_BOOKING',
		CANCEL_BOOKING: 'CANCEL_BOOKING'
	},
	Transmit: {
		BOOKING_CONFIRMED_CHANNEL: 'BOOKING_CONFIRMED_CHANNEL',
		BOOKING_CANCELED_CHANNEL: 'BOOKING_CANCELED_CHANNEL'
	}

}