export enum TransactionStatus {
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE'
}

export enum Procedure {
  GET_ALL_BOOKING_DETAILS = 'GET_ALL_BOOKING_DETAILS',
  CREATE_BOOKING = 'CREATE_BOOKING',
  CANCEL_BOOKING = 'CANCEL_BOOKING'
}

export enum Transmit {
  BOOKING_CONFIRMED_CHANNEL = 'BOOKING_CONFIRMED_CHANNEL',
  BOOKING_CANCELED_CHANNEL = 'BOOKING_CANCELED_CHANNEL'
}
